from . import (
    compress, convert, edit_metadata, extract_images, extract_text, flatten,
    grayscale, header_footer, interleave, merge, organize, page_numbers,
    pdf_to_format, pdf_to_html, pdf_to_images, pdf_to_markdown, protect,
    rename, rotate, sign_pdf, split, split_pages, unlock, watermark,
    webpage_to_pdf,
)

TOOLS = {
    'convert_to_pdf': {
        'name': 'Convert to PDF',
        'description': 'Convert images (PNG, JPG, WEBP…) and Office files (PPTX, DOCX…) to PDF',
        'accepts': ['png','jpg','jpeg','gif','bmp','tiff','webp','pptx','ppt','docx','doc','xlsx','xls'],
        'icon': 'convert',
        'params': [],
        'func': convert.run,
    },
    'merge': {
        'name': 'Merge PDFs',
        'description': 'Combine multiple PDFs into a single document in upload order',
        'accepts': ['pdf'],
        'icon': 'merge',
        'params': [],
        'func': merge.run,
    },
    'split': {
        'name': 'Split PDF',
        'description': 'Drag pages into groups — each group becomes one output PDF',
        'accepts': ['pdf'],
        'icon': 'split',
        'interactive': True,
        'params': [
            {'id': 'groups', 'name': 'Groups', 'type': 'hidden', 'default': None},
        ],
        'func': split.run,
    },
    'split_pages': {
        'name': 'Split to Pages',
        'description': 'Explode a PDF into one file per page',
        'accepts': ['pdf'],
        'icon': 'split',
        'params': [],
        'func': split_pages.run,
    },
    'compress': {
        'name': 'Compress PDF',
        'description': 'Shrink file size using Ghostscript image downsampling and stream compression',
        'accepts': ['pdf'],
        'icon': 'compress',
        'params': [
            {
                'id': 'level', 'name': 'Compression level', 'type': 'select',
                'options': ['light', 'medium', 'aggressive'], 'default': 'medium',
            },
        ],
        'func': compress.run,
    },
    'page_numbers': {
        'name': 'Add Page Numbers',
        'description': 'Stamp sequential page numbers onto every page',
        'accepts': ['pdf'],
        'icon': 'page_numbers',
        'params': [
            {
                'id': 'position', 'name': 'Position', 'type': 'select',
                'options': ['bottom-center','bottom-left','bottom-right',
                            'top-center','top-left','top-right'],
                'default': 'bottom-center',
            },
            {'id': 'start',     'name': 'Start at',  'type': 'number', 'default': 1},
            {'id': 'prefix',    'name': 'Prefix',     'type': 'text',   'default': '',    'placeholder': 'e.g. Page '},
            {'id': 'font_size', 'name': 'Font size',  'type': 'number', 'default': 11},
        ],
        'func': page_numbers.run,
    },
    'header_footer': {
        'name': 'Header & Footer',
        'description': 'Stamp custom text at the top and/or bottom of every page',
        'accepts': ['pdf'],
        'icon': 'header_footer',
        'params': [
            {
                'id': 'header_text', 'name': 'Header text', 'type': 'template_text',
                'default': '', 'placeholder': 'e.g. CONFIDENTIAL  or  {date}',
                'tokens': ['{page}', '{total}', '{date}', '{datetime}'],
            },
            {
                'id': 'footer_text', 'name': 'Footer text', 'type': 'template_text',
                'default': '{page} / {total}', 'placeholder': 'e.g. {page} / {total}',
                'tokens': ['{page}', '{total}', '{date}', '{datetime}'],
            },
            {'id': 'font_size',   'name': 'Font size',   'type': 'number', 'default': 10},
            {'id': 'margin',      'name': 'Margin (pt)', 'type': 'number', 'default': 20},
        ],
        'func': header_footer.run,
    },
    'rotate': {
        'name': 'Rotate Pages',
        'description': 'Rotate all or selected pages by 90 / 180 / 270°',
        'accepts': ['pdf'],
        'icon': 'rotate',
        'params': [
            {
                'id': 'angle', 'name': 'Angle', 'type': 'select',
                'options': ['90','180','270'], 'default': '90',
            },
            {
                'id': 'pages', 'name': 'Pages', 'type': 'text',
                'default': 'all', 'placeholder': 'all  or  1,3,5-8',
            },
        ],
        'func': rotate.run,
    },
    'organize_pages': {
        'name': 'Organize Pages',
        'description': 'Drag and drop to reorder or remove pages before continuing',
        'accepts': ['pdf'],
        'icon': 'organize',
        'interactive': True,
        'params': [
            {'id': 'order', 'name': 'Page order', 'type': 'hidden', 'default': None},
        ],
        'func': organize.run,
    },
    'watermark': {
        'name': 'Watermark',
        'description': 'Stamp diagonal text across every page',
        'accepts': ['pdf'],
        'icon': 'watermark',
        'params': [
            {'id': 'text',      'name': 'Text',      'type': 'text',   'default': 'CONFIDENTIAL'},
            {'id': 'font_size', 'name': 'Font size', 'type': 'number', 'default': 52},
            {'id': 'color',     'name': 'Color',     'type': 'color',  'default': '#aaaaaa'},
        ],
        'func': watermark.run,
    },
    'rename': {
        'name': 'Rename PDFs',
        'description': 'Rename output files using a template or custom names per file',
        'accepts': ['pdf'],
        'icon': 'rename',
        'params': [
            {
                'id': 'template', 'name': 'Name template', 'type': 'template_text',
                'default': '{original}',
                'placeholder': 'e.g. invoice_{date}',
                'tokens': ['{original}', '{date}', '{time}', '{datetime}', '{index}'],
            },
            {
                'id': 'ask', 'name': 'Ask me before naming (pause to enter each name)',
                'type': 'checkbox', 'default': False,
            },
        ],
        'func': rename.run,
    },
    'protect': {
        'name': 'Protect PDF',
        'description': 'Encrypt with a password to restrict opening or editing',
        'accepts': ['pdf'],
        'icon': 'protect',
        'params': [
            {'id': 'user_password',  'name': 'Open password',   'type': 'text', 'default': '', 'placeholder': 'Leave blank for no open password'},
            {'id': 'owner_password', 'name': 'Owner password',  'type': 'text', 'default': '', 'placeholder': 'Required to change permissions'},
            {'id': 'allow_print',    'name': 'Allow printing',  'type': 'checkbox', 'default': True},
            {'id': 'allow_copy',     'name': 'Allow copying text', 'type': 'checkbox', 'default': True},
            {'id': 'allow_modify',   'name': 'Allow editing',   'type': 'checkbox', 'default': False},
        ],
        'func': protect.run,
    },
    'unlock': {
        'name': 'Unlock PDF',
        'description': 'Remove password protection (you must know the password)',
        'accepts': ['pdf'],
        'icon': 'unlock',
        'params': [
            {'id': 'password', 'name': 'Password', 'type': 'text', 'default': '', 'placeholder': 'Enter the PDF password'},
        ],
        'func': unlock.run,
    },
    'pdf_to_images': {
        'name': 'PDF to Images',
        'description': 'Render each page as PNG or JPEG — delivered as a ZIP',
        'accepts': ['pdf'],
        'icon': 'pdf_to_images',
        'params': [
            {
                'id': 'format', 'name': 'Format', 'type': 'select',
                'options': ['PNG', 'JPEG'], 'default': 'PNG',
            },
            {'id': 'dpi',     'name': 'DPI',     'type': 'number', 'default': 150},
            {'id': 'quality', 'name': 'JPEG quality (1-100)', 'type': 'number', 'default': 85},
        ],
        'func': pdf_to_images.run,
    },
    'pdf_to_format': {
        'name': 'PDF to Word / PowerPoint',
        'description': 'Convert PDF to an editable DOCX or PPTX file',
        'accepts': ['pdf'],
        'icon': 'pdf_to_format',
        'params': [
            {
                'id': 'format', 'name': 'Output format', 'type': 'select',
                'options': ['DOCX', 'PPTX'], 'default': 'DOCX',
            },
        ],
        'func': pdf_to_format.run,
    },
    'extract_text': {
        'name': 'Extract Text',
        'description': 'Pull all text out of a PDF and save as a .txt file',
        'accepts': ['pdf'],
        'icon': 'extract_text',
        'params': [
            {'id': 'include_page_numbers', 'name': 'Include page labels', 'type': 'checkbox', 'default': True},
        ],
        'func': extract_text.run,
    },
    'edit_metadata': {
        'name': 'Edit Metadata',
        'description': 'Set the title, author, subject, and keywords stored inside the PDF',
        'accepts': ['pdf'],
        'icon': 'edit_metadata',
        'params': [
            {'id': 'title',    'name': 'Title',    'type': 'text', 'default': '', 'placeholder': 'Document title'},
            {'id': 'author',   'name': 'Author',   'type': 'text', 'default': '', 'placeholder': 'Author name'},
            {'id': 'subject',  'name': 'Subject',  'type': 'text', 'default': '', 'placeholder': 'Subject or description'},
            {'id': 'keywords', 'name': 'Keywords', 'type': 'text', 'default': '', 'placeholder': 'comma-separated keywords'},
            {'id': 'creator',  'name': 'Creator',  'type': 'text', 'default': '', 'placeholder': 'Creating application'},
        ],
        'func': edit_metadata.run,
    },
    'grayscale': {
        'name': 'Grayscale',
        'description': 'Convert all pages to black and white / grayscale',
        'accepts': ['pdf'],
        'icon': 'grayscale',
        'params': [
            {'id': 'dpi', 'name': 'DPI (higher = better quality)', 'type': 'number', 'default': 150},
        ],
        'func': grayscale.run,
    },
    'interleave': {
        'name': 'Interleave Pages',
        'description': 'Fix double-sided scans by alternating pages from two PDFs',
        'accepts': ['pdf'],
        'icon': 'interleave',
        'params': [
            {'id': 'reverse_second', 'name': 'Reverse second file (typical for duplex scanners)', 'type': 'checkbox', 'default': True},
        ],
        'func': interleave.run,
    },
    'flatten': {
        'name': 'Flatten PDF',
        'description': 'Bake in annotations and form fields by rendering each page to an image',
        'accepts': ['pdf'],
        'icon': 'flatten',
        'params': [
            {'id': 'dpi', 'name': 'DPI (higher = better quality)', 'type': 'number', 'default': 150},
        ],
        'func': flatten.run,
    },
    'extract_images': {
        'name': 'Extract Images',
        'description': 'Pull out all embedded images from a PDF as a ZIP',
        'accepts': ['pdf'],
        'icon': 'extract_images',
        'params': [],
        'func': extract_images.run,
    },
    'pdf_to_markdown': {
        'name': 'PDF to Markdown',
        'description': 'Convert PDF content to a clean Markdown (.md) file',
        'accepts': ['pdf'],
        'icon': 'pdf_to_markdown',
        'params': [],
        'func': pdf_to_markdown.run,
    },
    'sign_pdf': {
        'name': 'Sign PDF',
        'description': 'Draw a signature box on any page — type your name, drag to position',
        'accepts': ['pdf'],
        'icon': 'sign_pdf',
        'interactive': True,
        'params': [
            {'id': 'signature_text', 'name': 'Signature', 'type': 'text',  'default': '', 'placeholder': 'Your name or initials'},
            {'id': 'color',          'name': 'Color',     'type': 'color', 'default': '#1a1a2e'},
            {'id': 'placement',      'name': 'Placement', 'type': 'hidden', 'default': None},
        ],
        'func': sign_pdf.run,
    },
    'pdf_to_html': {
        'name': 'PDF to Webpage',
        'description': 'Convert PDF to a self-contained HTML file viewable in any browser',
        'accepts': ['pdf'],
        'icon': 'pdf_to_html',
        'params': [
            {'id': 'include_images', 'name': 'Embed page images', 'type': 'checkbox', 'default': True},
            {'id': 'image_dpi',      'name': 'Image DPI',         'type': 'number',   'default': 120},
        ],
        'func': pdf_to_html.run,
    },
    'webpage_to_pdf': {
        'name': 'Webpage to PDF',
        'description': 'Render any URL to a PDF using a headless browser',
        'accepts': ['pdf'],
        'icon': 'convert',
        'params': [
            {'id': 'url',         'name': 'URL',       'type': 'text',   'default': '', 'placeholder': 'https://example.com'},
            {'id': 'page_format', 'name': 'Page size', 'type': 'select', 'options': ['A4', 'Letter'], 'default': 'A4'},
            {'id': 'wait_until',  'name': 'Wait for',  'type': 'select', 'options': ['networkidle', 'load'], 'default': 'networkidle'},
        ],
        'func': webpage_to_pdf.run,
    },
}
